version: '3'
services:

  senzing:
    build:
        context: .
        dockerfile: senzing.Dockerfile
    image: senzing/senzing_starter_kit
    volumes:
      - senzing-output:/output

  kineviz:
    build:
        context: .
        dockerfile: kineviz.Dockerfile
    volumes:
      - senzing-output:/input

volumes:
  senzing-output: