version: '3'
services:

  file-writer:
    container_name: file-writer
    image: senzing/senzing_starter_kit
    networks:
      - senzing
    read_only: true
    volumes:
      - senzing-output:/export

  file-reader:
    container_name: file-reader
    command:
      - sh
      - -c
      - sleep 1; ls /input/;
    depends_on:
      - file-writer
    image: busybox:${SENZING_DOCKER_IMAGE_VERSION_BUSYBOX:-latest}
    networks:
      - senzing
    read_only: true
    volumes:
      - senzing-output:/input

networks:
  senzing:
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}

volumes:
  senzing-output: